// One-off build-time script: reads assets/trip.csv and emits src/data/seedTrip.ts
// Run: node scripts/parseCsv.js
const fs = require('fs');
const path = require('path');
const Papa = require('papaparse');

const csvPath = path.join(__dirname, '..', 'assets', 'trip.csv');
const outPath = path.join(__dirname, '..', 'src', 'data', 'seedTrip.ts');

const content = fs.readFileSync(csvPath, 'utf8');
const parsed = Papa.parse(content, { header: true, skipEmptyLines: true });

const rows = parsed.data.filter((r) => r.Day && String(r.Day).trim() !== '');

const num = (v) => {
  const n = parseFloat(String(v ?? '0').replace(/,/g, ''));
  return Number.isFinite(n) ? n : 0;
};

const days = rows.map((r) => ({
  dayNum: parseInt(String(r.Day).trim(), 10),
  date: String(r.Date || '').trim(),
  stayCity: String(r.Stay || '').trim(),
  fromCity: String(r.From || '').trim(),
  toCity: String(r.To || '').trim(),
  imageUrl: String(r.Images || '').trim(),
  accommodationName: String(r['Name of Accommodation'] || '').trim(),
  address: String(r.Address || '').trim(),
  location: String(r.Location || '').trim(),
  agent: String(r.Agent || '').trim(),
  paymentStatus: String(r.Payment || '').trim(),
  travelDetails: String(r['Travel Details'] || '').trim(),
  summary: String(r["Summary of day's events"] || '').trim(),
  budgeted: {
    hotels: num(r.Hotels),
    flights: num(r.Flights),
    ferry: num(r.Ferry),
    train: num(r.Train),
    others: num(r.Others),
  },
}));

const trip = {
  id: 'thailand-apr-2026',
  title: 'Thailand — Apr 27 to May 9, 2026',
  startDate: '2026-04-27',
  endDate: '2026-05-09',
  homeCurrency: 'INR',
  localCurrency: 'THB',
};

const banner = '// AUTO-GENERATED by scripts/parseCsv.js — do not edit by hand.\n// Regenerate: `node scripts/parseCsv.js`\n';
const body =
  banner +
  `\nimport type { SeedTrip, SeedDay } from './types';\n\n` +
  `export const SEED_TRIP: SeedTrip = ${JSON.stringify(trip, null, 2)};\n\n` +
  `export const SEED_DAYS: SeedDay[] = ${JSON.stringify(days, null, 2)};\n`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, body);
console.log(`Wrote ${days.length} days to ${outPath}`);
