// AUTO-GENERATED by scripts/parseCsv.js — do not edit by hand.
// Regenerate: `node scripts/parseCsv.js`

import type { SeedTrip, SeedDay } from './types';

export const SEED_TRIP: SeedTrip = {
  "id": "thailand-apr-2026",
  "title": "Thailand — Apr 27 to May 9, 2026",
  "startDate": "2026-04-27",
  "endDate": "2026-05-09",
  "homeCurrency": "INR",
  "localCurrency": "THB"
};

export const SEED_DAYS: SeedDay[] = [
  {
    "dayNum": 1,
    "date": "Mon, Apr 27, 2026",
    "stayCity": "Phuket",
    "fromCity": "Bengaluru",
    "toCity": "Phuket",
    "imageUrl": "https://images.unsplash.com/photo-1641546373508-635403c24289?auto=format&fit=crop&w=1600&q=75",
    "accommodationName": "Patong / Kata Hotel (3 nights - TBD)",
    "address": "Patong or Kata Beach, Phuket, Thailand",
    "location": "",
    "agent": "",
    "paymentStatus": "Pending",
    "travelDetails": "Akasa Air BLR 09:20 -> HKT 15:05 (approx 4h 15m)\nBOOKED via Akasa Air\nReach BLR airport by 07:00 (2 hrs before intl)\nCarry THB 15,000 cash or withdraw at HKT arrival ATM\nAirport taxi to Patong ~600 THB, 45 min (book via hotel for fixed price)",
    "summary": "Arrive Phuket ~15:05. Immigration + baggage (~1 hr). Taxi to Patong. Check in, freshen up. Evening: beach walk, dinner on Bangla Rd — or quieter Kata/Karon if preferred.",
    "budgeted": {
      "hotels": 0,
      "flights": 0,
      "ferry": 0,
      "train": 0,
      "others": 0
    }
  },
  {
    "dayNum": 2,
    "date": "Tue, Apr 28, 2026",
    "stayCity": "Phuket",
    "fromCity": "",
    "toCity": "",
    "imageUrl": "https://images.unsplash.com/photo-1534008897995-27a23e859048?auto=format&fit=crop&w=1600&q=75",
    "accommodationName": "Patong / Kata Hotel",
    "address": "Patong or Kata Beach, Phuket, Thailand",
    "location": "",
    "agent": "Klook / Hotel desk",
    "paymentStatus": "Pending",
    "travelDetails": "Tour van pickup from hotel 07:30\nSpeedboat from Rassada or Chalong pier\nReturn 18:00",
    "summary": "Phi Phi Islands full-day speedboat tour — Maya Bay, Pileh Lagoon, Viking Cave, Bamboo Island, Monkey Beach, snorkel stops.",
    "budgeted": {
      "hotels": 0,
      "flights": 0,
      "ferry": 0,
      "train": 0,
      "others": 0
    }
  },
  {
    "dayNum": 3,
    "date": "Wed, Apr 29, 2026",
    "stayCity": "Phuket",
    "fromCity": "",
    "toCity": "",
    "imageUrl": "https://images.unsplash.com/photo-1757489810186-0456b4aa61ba?auto=format&fit=crop&w=1600&q=75",
    "accommodationName": "Patong / Kata Hotel",
    "address": "Patong or Kata Beach, Phuket, Thailand",
    "location": "",
    "agent": "",
    "paymentStatus": "Pending",
    "travelDetails": "Half-day private driver ~1,500 THB OR rent scooter ~300 THB\nGrab also works",
    "summary": "Big Buddha (morning) → Phuket Old Town (lunch + walking) → Promthep Cape (sunset). Dress code at Big Buddha (shoulders + knees). Old Town Sunday Walking Street closed today (Wed). Promthep arrive 45 min before sunset.",
    "budgeted": {
      "hotels": 0,
      "flights": 0,
      "ferry": 0,
      "train": 0,
      "others": 0
    }
  },
  {
    "dayNum": 4,
    "date": "Thu, Apr 30, 2026",
    "stayCity": "Krabi",
    "fromCity": "Phuket",
    "toCity": "Krabi",
    "imageUrl": "https://images.unsplash.com/photo-1671591239011-332e3e7d746c?auto=format&fit=crop&w=1600&q=75",
    "accommodationName": "Ao Nang Hotel (3 nights - TBD)",
    "address": "Ao Nang, Krabi, Thailand",
    "location": "",
    "agent": "12go.asia / Hotel",
    "paymentStatus": "Pending",
    "travelDetails": "Private van Phuket -> Ao Nang hotel, 2.5 hrs, ~1,800 THB total\nDepart Phuket 09:00 -> arrive Ao Nang 12:00\nBook van 1 day in advance via hotel or 12go.asia",
    "summary": "Morning transfer to Krabi. Afternoon at Ao Nang beach, evening fire shows on the beach + seafood dinner.",
    "budgeted": {
      "hotels": 0,
      "flights": 0,
      "ferry": 0,
      "train": 0,
      "others": 0
    }
  },
  {
    "dayNum": 5,
    "date": "Fri, May 1, 2026",
    "stayCity": "Krabi",
    "fromCity": "",
    "toCity": "",
    "imageUrl": "https://images.unsplash.com/photo-1532370184535-22cec5ca8480?auto=format&fit=crop&w=1600&q=75",
    "accommodationName": "Ao Nang Hotel",
    "address": "Ao Nang, Krabi, Thailand",
    "location": "",
    "agent": "Klook / Hotel desk",
    "paymentStatus": "Pending",
    "travelDetails": "Tour boat from Ao Nang pier\nLongtail cheaper, speedboat faster\n~1,200 THB/person for longtail\nLabour Day holiday in Thailand — expect crowds",
    "summary": "Krabi 4-Islands tour by longtail or speedboat — Phra Nang Cave, Poda, Chicken Island, Tup Island sandbar, Railay finish.",
    "budgeted": {
      "hotels": 0,
      "flights": 0,
      "ferry": 0,
      "train": 0,
      "others": 0
    }
  },
  {
    "dayNum": 6,
    "date": "Sat, May 2, 2026",
    "stayCity": "Koh Samui",
    "fromCity": "Krabi",
    "toCity": "Koh Samui",
    "imageUrl": "https://images.unsplash.com/photo-1530948990335-1eb93cbe6430?auto=format&fit=crop&w=1600&q=75",
    "accommodationName": "Bophut / Chaweng Hotel (3 nights - TBD)",
    "address": "Bophut or Chaweng Beach, Koh Samui, Thailand",
    "location": "",
    "agent": "12go.asia",
    "paymentStatus": "Pending",
    "travelDetails": "Lomprayah or Phantip combo ticket from Ao Nang\nPickup 06:30 -> minivan 3.5 hrs -> Donsak pier -> catamaran 1.5 hrs -> Nathon pier -> taxi 30 min\nArrive Samui hotel ~14:30\nBook combo ticket on 12go.asia 3-4 days out (~1,200 THB/person, includes hotel pickup)\nTake Dramamine if prone to seasickness",
    "summary": "Krabi -> Koh Samui full travel day via bus + ferry combo. Arrive Samui afternoon, settle in at Bophut, sunset + dinner at Fisherman's Village (18:00).",
    "budgeted": {
      "hotels": 0,
      "flights": 0,
      "ferry": 0,
      "train": 0,
      "others": 0
    }
  },
  {
    "dayNum": 7,
    "date": "Sun, May 3, 2026",
    "stayCity": "Koh Samui",
    "fromCity": "",
    "toCity": "",
    "imageUrl": "https://images.unsplash.com/photo-1533604145636-765f22ac7352?auto=format&fit=crop&w=1600&q=75",
    "accommodationName": "Bophut / Chaweng Hotel",
    "address": "Bophut or Chaweng Beach, Koh Samui, Thailand",
    "location": "",
    "agent": "Klook / Hotel desk",
    "paymentStatus": "Pending",
    "travelDetails": "Tour pickup from hotel 07:30\nSpeedboat from Bophut or Maenam pier\nReturn 17:30\n~2,500 THB/person\nBook 2-3 days out\nWeather-dependent — check forecast night before",
    "summary": "Ang Thong National Marine Park full-day speedboat tour — 42 islands, emerald lagoon, viewpoint hike, kayaking in hidden lagoon. THE headline Samui day.",
    "budgeted": {
      "hotels": 0,
      "flights": 0,
      "ferry": 0,
      "train": 0,
      "others": 0
    }
  },
  {
    "dayNum": 8,
    "date": "Mon, May 4, 2026",
    "stayCity": "Koh Samui",
    "fromCity": "",
    "toCity": "",
    "imageUrl": "https://images.unsplash.com/photo-1577375837944-47617314bfd9?auto=format&fit=crop&w=1600&q=75",
    "accommodationName": "Bophut / Chaweng Hotel",
    "address": "Bophut or Chaweng Beach, Koh Samui, Thailand",
    "location": "",
    "agent": "",
    "paymentStatus": "Pending",
    "travelDetails": "Rent scooter 300 THB/day OR hire driver half-day ~1,500 THB\nSamui roads are easy, traffic light",
    "summary": "Samui island loop: Wat Phra Yai (Big Buddha) -> Hin Ta / Hin Yai rocks -> Na Muang Waterfall -> afternoon at Chaweng Beach -> dinner at Chaweng or Bophut. Skip elephant rides at Na Muang (ethics).",
    "budgeted": {
      "hotels": 0,
      "flights": 0,
      "ferry": 0,
      "train": 0,
      "others": 0
    }
  },
  {
    "dayNum": 9,
    "date": "Tue, May 5, 2026",
    "stayCity": "Bangkok",
    "fromCity": "Koh Samui",
    "toCity": "Bangkok",
    "imageUrl": "https://images.unsplash.com/photo-1582541537694-965be7aed707?auto=format&fit=crop&w=1600&q=75",
    "accommodationName": "Bangkok Hotel (4 nights - TBD)",
    "address": "Bangkok, Thailand",
    "location": "",
    "agent": "AirAsia / 12go.asia",
    "paymentStatus": "Pending",
    "travelDetails": "Taxi Samui hotel -> Lipa Noi pier (30 min, ~500 THB)\nRaja Ferry 08:00 Lipa Noi -> Donsak (1.5 hrs, ~200 THB)\nShuttle bus Donsak -> Surat Thani Airport URT (1.5 hrs, ~300 THB)\nAirAsia URT 15:35 -> DMK 16:50 (1h 15min)\nDMK -> hotel: airport bus A1 to BTS Mo Chit 50 THB, or taxi ~400 THB (45-60 min)\nACTION REQUIRED: REBOOK AirAsia FD flight from WED 6 MAY to TUE 5 MAY via airasia.com -> Manage Booking. Change fee ~700-1,200 THB + fare difference\nPre-book ferry+bus combo on 12go.asia",
    "summary": "Samui -> Surat Thani -> fly to Bangkok (DMK). Check in at Bangkok hotel, dinner near hotel. Keep evening light.",
    "budgeted": {
      "hotels": 0,
      "flights": 0,
      "ferry": 0,
      "train": 0,
      "others": 0
    }
  },
  {
    "dayNum": 10,
    "date": "Wed, May 6, 2026",
    "stayCity": "Bangkok",
    "fromCity": "",
    "toCity": "",
    "imageUrl": "https://images.unsplash.com/photo-1613672803979-a6edfc5a179b?auto=format&fit=crop&w=1600&q=75",
    "accommodationName": "Bangkok Hotel",
    "address": "Bangkok, Thailand",
    "location": "",
    "agent": "",
    "paymentStatus": "Pending",
    "travelDetails": "Grab or MRT to Grand Palace\nWalk between Grand Palace and Wat Pho\nChao Phraya ferry to Wat Arun (5 THB one-way)",
    "summary": "Temple triple crown: Grand Palace (08:30 sharp) -> Wat Pho Reclining Buddha (+ optional Thai massage 320 THB/30 min) -> cross river by ferry to Wat Arun. Evening: rooftop bar (Sky Bar / Vertigo) or Khao San Road. Grand Palace dress code STRICT: long pants/skirt, covered shoulders, closed shoes. Tickets 500 THB.",
    "budgeted": {
      "hotels": 0,
      "flights": 0,
      "ferry": 0,
      "train": 0,
      "others": 0
    }
  },
  {
    "dayNum": 11,
    "date": "Thu, May 7, 2026",
    "stayCity": "Bangkok",
    "fromCity": "",
    "toCity": "",
    "imageUrl": "https://images.unsplash.com/photo-1759770176679-159a90565c50?auto=format&fit=crop&w=1600&q=75",
    "accommodationName": "Bangkok Hotel",
    "address": "Bangkok, Thailand",
    "location": "",
    "agent": "Klook / Hotel",
    "paymentStatus": "Pending",
    "travelDetails": "Hired private car RT ~2,500 THB (book via hotel day before)\nOR train from Krungthep Aphiwat Central ~20 THB each way (2 hrs)\nDepart 07:30 -> back in Bangkok 17:30\nDinner cruise 20:00",
    "summary": "Ayutthaya day trip — ancient Siamese capital. Wat Mahathat (Buddha head in tree roots), Wat Phra Si Sanphet, Wat Chaiwatthanaram. Guide at Wat Mahathat ~300 THB. Evening: Chao Phraya dinner cruise (Wonderful Pearl / Princess) ~1,500 THB incl. buffet — book on Klook.",
    "budgeted": {
      "hotels": 0,
      "flights": 0,
      "ferry": 0,
      "train": 0,
      "others": 0
    }
  },
  {
    "dayNum": 12,
    "date": "Fri, May 8, 2026",
    "stayCity": "Bangkok",
    "fromCity": "",
    "toCity": "",
    "imageUrl": "https://images.unsplash.com/photo-1735926005134-2ad67e8cf9e7?auto=format&fit=crop&w=1600&q=75",
    "accommodationName": "Bangkok Hotel",
    "address": "Bangkok, Thailand",
    "location": "",
    "agent": "",
    "paymentStatus": "Pending",
    "travelDetails": "River cruise: Sathorn pier\nMBK: BTS National Stadium\nChatuchak: BTS Mo Chit or MRT Chatuchak Park\nAsiatique: free shuttle boat from Sathorn pier",
    "summary": "SHOPPING DAY. Morning: Chao Phraya river cruise to ICONSIAM (shopping + lunch). Afternoon: MBK Center or Terminal 21. Evening 17:00-22:00: CHATUCHAK (Friday evening opens, plant/wholesale + many regular vendors, less chaotic than weekend). Alternative: Asiatique Riverfront (daily 16:00-midnight). ONLY shopping day — return flight Sat 08:05 rules out Chatuchak weekend. PACK BAGS TONIGHT. Back at hotel by 22:00 — 04:00 wake tomorrow.",
    "budgeted": {
      "hotels": 0,
      "flights": 0,
      "ferry": 0,
      "train": 0,
      "others": 0
    }
  },
  {
    "dayNum": 13,
    "date": "Sat, May 9, 2026",
    "stayCity": "Bangkok",
    "fromCity": "Bangkok",
    "toCity": "Bengaluru",
    "imageUrl": "https://images.unsplash.com/photo-1698584109673-12d97bc70d08?auto=format&fit=crop&w=1600&q=75",
    "accommodationName": "",
    "address": "",
    "location": "",
    "agent": "IndiGo",
    "paymentStatus": "Pending",
    "travelDetails": "IndiGo BKK 08:05 -> BLR 10:15 BOOKED\nINTERNATIONAL CHECK-IN CLOSES 60 MIN BEFORE = 07:05 CUTOFF\nReach airport by 05:30 absolute latest\nIndiGo usually operates from BKK Suvarnabhumi — verify on e-ticket\n04:00 wake -> 04:30 taxi -> 05:30 BKK\nGrab or pre-booked taxi hotel -> Suvarnabhumi, 45-60 min at this hour, ~400 THB\nAirport Rail Link doesn't start until 05:30 — taxi only reliable option\nBook Grab scheduled night before, or ask hotel for 04:30 taxi\nCarry passport + boarding pass printout\nKeep ₹500 for airport taxi at BLR arrival",
    "summary": "Very early departure. No sightseeing — just get to airport.",
    "budgeted": {
      "hotels": 0,
      "flights": 0,
      "ferry": 0,
      "train": 0,
      "others": 0
    }
  }
];
